import type { Portfolio } from "@/schemas/portfolio";
import { PORTFOLIO_TSX } from "./standaloneRenderer";

const GOOGLE_FONTS_HREF =
  "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Roboto:wght@400;500;700&family=Poppins:wght@400;500;600;700&family=Montserrat:wght@400;500;600;700&family=Space+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;700&display=swap";

function esc(s: string) {
  return s.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

/**
 * Produce the complete file map for a standalone, deployable Next.js portfolio
 * project. The result has no runtime dependency on the builder platform.
 */
export function generateProjectFiles(data: Portfolio): Record<string, string> {
  const seo = data.seo;
  const projectName = (data.sections.hero.name || "portfolio")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  const packageJson = {
    name: projectName || "portfolio",
    version: "1.0.0",
    private: true,
    scripts: { dev: "next dev", build: "next build", start: "next start" },
    dependencies: {
      "@emotion/cache": "^11.14.0",
      "@emotion/react": "^11.14.0",
      "@emotion/styled": "^11.14.0",
      "@mui/material": "^9.1.0",
      "@mui/material-nextjs": "^9.1.0",
      next: "16.2.7",
      react: "19.2.4",
      "react-dom": "19.2.4",
    },
    devDependencies: {
      "@types/node": "^20",
      "@types/react": "^19",
      "@types/react-dom": "^19",
      typescript: "^5",
    },
  };

  const tsconfig = {
    compilerOptions: {
      target: "ES2017",
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      plugins: [{ name: "next" }],
      paths: { "@/*": ["./*"] },
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"],
  };

  const layout = `import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";
import "./globals.css";

export const metadata: Metadata = {
  title: "${esc(seo.metaTitle)}",
  description: "${esc(seo.metaDescription)}",
  keywords: ${JSON.stringify(seo.keywords)},
  openGraph: {
    title: "${esc(seo.metaTitle)}",
    description: "${esc(seo.metaDescription)}",
    images: ${seo.ogImage ? `["${esc(seo.ogImage)}"]` : "[]"},
  },
  twitter: {
    card: "summary_large_image",
    images: ${seo.twitterImage ? `["${esc(seo.twitterImage)}"]` : "[]"},
  },
  ${seo.canonicalUrl ? `alternates: { canonical: "${esc(seo.canonicalUrl)}" },` : ""}
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="stylesheet" href="${GOOGLE_FONTS_HREF}" />
      </head>
      <body style={{ margin: 0 }}>
        <AppRouterCacheProvider options={{ key: "mui" }}>{children}</AppRouterCacheProvider>
      </body>
    </html>
  );
}
`;

  const page = `import Portfolio from "@/components/Portfolio";

export default function Home() {
  return <Portfolio />;
}
`;

  const globals = `html, body { padding: 0; margin: 0; }
* { box-sizing: border-box; }
a { color: inherit; text-decoration: none; }
`;

  const nextConfig = `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: { remotePatterns: [{ protocol: "https", hostname: "**" }] },
};

export default nextConfig;
`;

  const gitignore = `/node_modules
/.next
/out
.env*
.DS_Store
`;

  const readme = `# ${data.sections.hero.name} — Portfolio

A standalone portfolio website generated by **Portfolio Builder**. It is fully
independent and can be deployed to Vercel, Netlify, or any Node host.

## Getting started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open http://localhost:3000.

## Editing content

All content lives in [\`content/portfolio.json\`](content/portfolio.json) — the
single source of truth. Edit it and the site updates. The renderer is in
\`components/Portfolio.tsx\`.

## Deploy

\`\`\`bash
npm run build && npm start
\`\`\`

Or push to a Git repo and import it on Vercel.
`;

  return {
    "package.json": JSON.stringify(packageJson, null, 2),
    "tsconfig.json": JSON.stringify(tsconfig, null, 2),
    "next.config.ts": nextConfig,
    ".gitignore": gitignore,
    "README.md": readme,
    "app/layout.tsx": layout,
    "app/page.tsx": page,
    "app/globals.css": globals,
    "components/Portfolio.tsx": PORTFOLIO_TSX,
    "content/portfolio.json": JSON.stringify(data, null, 2),
  };
}

/** Build a ZIP blob of the standalone project and trigger a browser download. */
export async function downloadProjectZip(data: Portfolio): Promise<void> {
  const JSZip = (await import("jszip")).default;
  const zip = new JSZip();
  const files = generateProjectFiles(data);
  const root = "portfolio-export";
  for (const [path, content] of Object.entries(files)) {
    zip.file(`${root}/${path}`, content);
  }
  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${root}.zip`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
